language: java
install:
script:
  - sed -i "s|TargetDirectory|$(pwd)/target|g" src/main/docker/post-receive
  - sed -i "s|CheckoutDirectory|$(pwd)/frinex-repositories|g" src/main/docker/post-receive
  - sed -i "s|RepositoriesDirectory|$(pwd)/frinex-repositories/git|g" src/main/docker/post-receive
  - sed -i "s|ScriptsDirectory|$(pwd)|g" src/main/docker/post-receive
  - sed -i "s|TargetDirectory|$(pwd)/target|g" src/main/docker/publish.properties
  - sed -i "s|CheckoutDirectory|$(pwd)/frinex-repositories|g" src/main/docker/publish.properties
  - sed -i "s|RepositoriesDirectory|$(pwd)/frinex-repositories/git|g" src/main/docker/publish.properties
  - sed -i "s|ScriptsDirectory|$(pwd)|g" src/main/docker/publish.properties
  - sed -i "s|TargetDirectory|$(pwd)/target|g" src/main/docker/create_frinex_build_repository.sh
  - sed -i "s|CheckoutDirectory|$(pwd)/frinex-repositories|g" src/main/docker/create_frinex_build_repository.sh
  - sed -i "s|RepositoriesDirectory|$(pwd)/frinex-repositories/git|g" src/main/docker/create_frinex_build_repository.sh
  - sed -i "s|ScriptsDirectory|$(pwd)|g" src/main/docker/create_frinex_build_repository.sh
  - sed -i "s|chown|#chown|g" src/main/docker/create_frinex_build_repository.sh

  - mkdir target
  - mkdir incoming
  - mkdir incoming/commits
  - mkdir incoming/static
  - bash src/main/docker/create_frinex_build_repository.sh test-repository
  - pwd
  - ls
  - ls target
  - ls frinex-repositories
  - ls frinex-repositories/git
  - cd frinex-repositories/test-repository
  - echo "test" > test-experiment.xml
  - git add test-experiment.xml
  - git commit -m "test" test-experiment.xml; git push
  - echo " " >> test-experiment.xml
  - git commit -m "test" test-experiment.xml; git push
  - cd ../..
  - ls target
  - ls target/*
