language: java
install:
script:
  - sed -i "s|TargetDirectory|$(pwd)/../target|g" post-receive
  - sed -i "s|CheckoutDirectory|$(pwd)/../frinex-repositories|g" post-receive
  - sed -i "s|RepositoriesDirectory|$(pwd)/../frinex-repositories/git|g" post-receive
  - sed -i "s|ScriptsDirectory|$(pwd)|g" post-receive
  - sed -i "s|chown|#chown|g" create_frinex_build_repository.sh

  - bash create_frinex_build_repository.sh test-repository
  - pwd
  - cd ..
  - ls
  - ls target
  - ls target/*
  - ls frinex-repositories
  - ls frinex-repositories/git
  - cd frinex-repositories/test-repository
  - echo "test" > test-experiment.xml
  - git add test-experiment.xml
  - git commit -m "test" test-experiment.xml; git push
  - echo " " >> test-experiment.xml
  - git commit -m "test" test-experiment.xml; git push
  - cd ../..
  - ls target
  - ls target/*
