@startuml
title Overview of the Frinex build server when configured to deploy to separate tomcat servers for staging and production.

package "BuildServer" {
  GIT - [BuildProcess]
  [BuildProcess] - BuildListing
}

XML --> GIT
JSON --> GIT

package "Staging" {
  database "S_Postgres" {
    [S_ExperimentA_DB]
    [S_ExperimentB_DB]
    [S_ExperimentC_DB]
  }
  folder "S_Tomcat" {
    [S_ExperimentA] --> S_ExperimentA_DB
    [S_ExperimentB] --> S_ExperimentB_DB
    [S_ExperimentC] --> S_ExperimentC_DB
  }
  [S_CRON] --> S_Postgres 
}

package "Production" {
  database "P_Postgres" {
    [P_ExperimentA_DB]
    [P_ExperimentB_DB]
    [P_ExperimentC_DB]
  }
  folder "P_Tomcat" {
    [P_ExperimentA] --> P_ExperimentA_DB
    [P_ExperimentB] --> P_ExperimentB_DB
    [P_ExperimentC] --> P_ExperimentC_DB
  }
  [P_CRON] --> P_Postgres 
}

BuildServer --> ElectronApps
BuildServer --> MobileApps

BuildServer --> Staging
BuildServer --> Production

cloud WebAccess {
  http_host_80_S_ExperimentA --> S_ExperimentA
  http_host_80_S_ExperimentB --> S_ExperimentB
  http_host_80_S_ExperimentC --> S_ExperimentC
  http_host_80_P_ExperimentA --> P_ExperimentA
  http_host_80_P_ExperimentB --> P_ExperimentB
  http_host_80_P_ExperimentC --> P_ExperimentC
}

@enduml