#!/bin/bash
#
# Copyright (C) 2026 Max Planck Institute for Psycholinguistics
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

#
# @since 20 May 2026 12:34 PM (creation date)
# @author Peter Withers <peter.withers@mpi.nl>
#

# This script migrates the databases as required when moving to spring boot version 3.5.0 and GenerationType.IDENTITY



PGPASSFILE=/FrinexBuildService/frinex_db_user_authentication
export PGPASSFILE
appNameInternal="load_test_target"

if [[ "$appNameInternal" == "load_test_target" ]]; then
    tablesToUpdate=("data_deletion_log" "event_time" "group_data" "audio_data" "screen_data" "stimulus_response" "tag_data" "tag_pair_data" "time_stamp" "participant")
    for table in "${tablesToUpdate[@]}"; do
        echo "Processing GenerationType.IDENTITY on table: $table"
        max_id=$(PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -v ON_ERROR_STOP=1 -tAc "SELECT COALESCE(MAX(id),0) FROM '$table'")
        echo "max_id: $max_id"
        tableResult=$(PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -v ON_ERROR_STOP=1 -c "
        ALTER TABLE '$table' ALTER COLUMN id DROP DEFAULT,ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        SELECT setval(pg_get_serial_sequence('$table','id'), $max_id);
        ")
        echo "$tableResult"
    done
fi
