#!/bin/bash
#
# Copyright (C) 2026 Max Planck Institute for Psycholinguistics
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

#
# @since 20 May 2026 12:34 PM (creation date)
# @author Peter Withers <peter.withers@mpi.nl>
#

# This script migrates the databases as required when moving to spring boot version 3.5.0 and GenerationType.IDENTITY



PGPASSFILE=/FrinexBuildService/frinex_db_user_authentication
export PGPASSFILE
appNameInternal="load_test_target"

if [[ "$appNameInternal" == "load_test_target" ]]; then
    messageString="$messageString\nProcessing GenerationType.IDENTITY: $appNameInternal"
    tableResult=$(PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -v ON_ERROR_STOP=1 -tAc "
    DO \$\$
    DECLARE
        tbl TEXT;
        max_id BIGINT;
        id_is_identity TEXT;
        tables TEXT[] := ARRAY[
            'data_deletion_log', 'event_time', 'group_data', 'audio_data', 'screen_data', 'stimulus_response', 'tag_data', 'tag_pair_data', 'time_stamp', 'participant'
        ];
    BEGIN
        FOREACH tbl IN ARRAY tables
        LOOP
            -- Check if id column exists and whether it's already identity
            SELECT c.is_identity
            INTO id_is_identity
            FROM information_schema.columns c
            WHERE c.table_schema = 'public'
            AND c.table_name = tbl
            AND c.column_name = 'id';

            IF NOT FOUND THEN
                RAISE NOTICE 'Skipping %, no id column found', tbl;
                CONTINUE;
            END IF;

            IF id_is_identity = 'YES' THEN
                RAISE NOTICE 'Skipping %, already IDENTITY', tbl;
                CONTINUE;
            END IF;

            -- Get next starting value
            EXECUTE format('SELECT COALESCE(MAX(id),0) FROM %I', tbl)
            INTO max_id;

            -- Convert column
            EXECUTE format(
                'ALTER TABLE %I
                ALTER COLUMN id DROP DEFAULT,
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                tbl,
                max_id + 1
            );

            RAISE NOTICE 'Updated %, new identity starts at %', tbl, max_id + 1;
        END LOOP;
    END
    \$\$;
    SELECT 'TABLE_UPDATE_STATUS: SUCCESS';
    ")
    messageString="$messageString\n$tableResult"
    if [[ "$tableResult" == *"TABLE_UPDATE_STATUS: SUCCESS"* ]]; then
        echo "Sequence update completed successfully for tables: ${tablesToUpdate[*]} $messageString"
    else
        echo "Failed sequence update for tables: ${tablesToUpdate[*]} $messageString"
    fi
fi
