#!/bin/bash
#
# Copyright (C) 2026 Max Planck Institute for Psycholinguistics
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

#
# @since 20 May 2026 12:34 PM (creation date)
# @author Peter Withers <peter.withers@mpi.nl>
#

# This script migrates the databases as required when moving to spring boot version 3.5.0 and GenerationType.IDENTITY



PGPASSFILE=/FrinexBuildService/frinex_db_user_authentication
export PGPASSFILE
appNameList=("load_test_target" "with_stimulus_example")
for appNameInternal in "${appNameList[@]}"; do
    echo "Database: $appNameInternal"
    tablesToUpdate=("data_deletion_log" "event_time" "group_data" "audio_data" "screen_data" "stimulus_response" "tag_data" "tag_pair_data" "time_stamp" "participant")
    for table in "${tablesToUpdate[@]}"; do
        echo "Processing GenerationType.IDENTITY on table: $table"
        is_identity=$(PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -tAc "
        SELECT is_identity
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = '$table'
          AND column_name = 'id';
        ")
        is_identity=$(echo "$is_identity" | xargs)
        echo "is_identity: $is_identity"
        if [[ "$is_identity" == "NO" ]]; then
            PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -c \
                "ALTER TABLE $table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;"
            PGPASSWORD='DatabaseStagingPass' psql -h DatabaseStagingUrl -p DatabaseStagingPort -U frinex_${appNameInternal}_user -d "frinex_${appNameInternal}_db" -c \
                "SELECT setval(pg_get_serial_sequence('$table','id'), COALESCE((SELECT MAX(id) FROM $table),0));"
            echo "Done: $table"
        fi
    done
done
